In [1]:
import kagglehub

path = kagglehub.dataset_download("nodoubttome/skin-cancer9-classesisic")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/1.archive...

100%|██████████| 786M/786M [00:22<00:00, 36.0MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1

In [2]:
import os

print(path)
print(os.listdir(path))

/root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1
['Skin cancer ISIC The International Skin Imaging Collaboration']

In [3]:
import os

print("Dataset path:", path)
print("\nFiles/Folders:")
print(os.listdir(path))

Dataset path: /root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1

Files/Folders:
['Skin cancer ISIC The International Skin Imaging Collaboration']

In [4]:
for root, dirs, files in os.walk(path):
    print(root, "->", len(files), "files")
    if root.count(os.sep) - path.count(os.sep) >= 2:
        dirs[:] = []

/root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1 -> 0 files
/root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1/Skin cancer ISIC The International Skin Imaging Collaboration -> 0 files
/root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1/Skin cancer ISIC The International Skin Imaging Collaboration/Train -> 0 files
/root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1/Skin cancer ISIC The International Skin Imaging Collaboration/Test -> 0 files

In [5]:
import os

dataset_root = os.path.join(
    path,
    "Skin cancer ISIC The International Skin Imaging Collaboration"
)

train_dir = os.path.join(dataset_root, "Train")
test_dir = os.path.join(dataset_root, "Test")

print("Train path:", train_dir)
print("Test path:", test_dir)

print("\nTrain folders:")
print(os.listdir(train_dir))

print("\nTest folders:")
print(os.listdir(test_dir))

Train path: /root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1/Skin cancer ISIC The International Skin Imaging Collaboration/Train
Test path: /root/.cache/kagglehub/datasets/nodoubttome/skin-cancer9-classesisic/versions/1/Skin cancer ISIC The International Skin Imaging Collaboration/Test

Train folders:
['squamous cell carcinoma', 'pigmented benign keratosis', 'actinic keratosis', 'vascular lesion', 'melanoma', 'nevus', 'basal cell carcinoma', 'dermatofibroma', 'seborrheic keratosis']

Test folders:
['squamous cell carcinoma', 'pigmented benign keratosis', 'actinic keratosis', 'vascular lesion', 'melanoma', 'nevus', 'basal cell carcinoma', 'dermatofibroma', 'seborrheic keratosis']

In [6]:
print("TRAIN DATASET")
print("=" * 50)

for class_name in sorted(os.listdir(train_dir)):
    class_path = os.path.join(train_dir, class_name)

    if os.path.isdir(class_path):
        images = os.listdir(class_path)
        print(f"{class_name}: {len(images)} images")


print("\nTEST DATASET")
print("=" * 50)

for class_name in sorted(os.listdir(test_dir)):
    class_path = os.path.join(test_dir, class_name)

    if os.path.isdir(class_path):
        images = os.listdir(class_path)
        print(f"{class_name}: {len(images)} images")

TRAIN DATASET
==================================================
actinic keratosis: 114 images
basal cell carcinoma: 376 images
dermatofibroma: 95 images
melanoma: 438 images
nevus: 357 images
pigmented benign keratosis: 462 images
seborrheic keratosis: 77 images
squamous cell carcinoma: 181 images
vascular lesion: 139 images

TEST DATASET
==================================================
actinic keratosis: 16 images
basal cell carcinoma: 16 images
dermatofibroma: 16 images
melanoma: 16 images
nevus: 16 images
pigmented benign keratosis: 16 images
seborrheic keratosis: 3 images
squamous cell carcinoma: 16 images
vascular lesion: 3 images

In [7]:
import os
import shutil

# Selected classes
selected_classes = [
    "melanoma",
    "nevus",
    "pigmented benign keratosis",
    "basal cell carcinoma"
]

# Create a new dataset directory
selected_dataset = "/content/skin_cancer_4class"

train_selected = os.path.join(selected_dataset, "Train")
test_selected = os.path.join(selected_dataset, "Test")

os.makedirs(train_selected, exist_ok=True)
os.makedirs(test_selected, exist_ok=True)

# Copy selected classes
for class_name in selected_classes:

    # Train
    source_train = os.path.join(train_dir, class_name)
    destination_train = os.path.join(train_selected, class_name)

    shutil.copytree(
        source_train,
        destination_train,
        dirs_exist_ok=True
    )

    # Test
    source_test = os.path.join(test_dir, class_name)
    destination_test = os.path.join(test_selected, class_name)

    shutil.copytree(
        source_test,
        destination_test,
        dirs_exist_ok=True
    )

print("Selected dataset created successfully!")

Selected dataset created successfully!

In [8]:
for split in ["Train", "Test"]:

    split_path = os.path.join(selected_dataset, split)

    print(f"\n{split}")
    print("=" * 40)

    for class_name in selected_classes:

        class_path = os.path.join(split_path, class_name)

        count = len([
            f for f in os.listdir(class_path)
            if os.path.isfile(os.path.join(class_path, f))
        ])

        print(f"{class_name}: {count}")

Train
========================================
melanoma: 438
nevus: 357
pigmented benign keratosis: 462
basal cell carcinoma: 376

Test
========================================
melanoma: 16
nevus: 16
pigmented benign keratosis: 16
basal cell carcinoma: 16

In [9]:
import torch
import torchvision
import sklearn

print("PyTorch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cu128
Torchvision version: 0.26.0+cu128
GPU available: True
GPU: Tesla T4

In [10]:
from torchvision import datasets, transforms
from torch.utils.data import random_split, DataLoader

# Image size required by the pretrained models
IMG_SIZE = 224

# Dataset paths
train_path = "/content/skin_cancer_4class/Train"
test_path = "/content/skin_cancer_4class/Test"

# Basic preprocessing
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
])

# Load complete training dataset
full_train_dataset = datasets.ImageFolder(
    train_path,
    transform=transform
)

# Load test dataset
test_dataset = datasets.ImageFolder(
    test_path,
    transform=transform
)

print("Classes:", full_train_dataset.classes)
print("Number of training images:", len(full_train_dataset))
print("Number of test images:", len(test_dataset))

Classes: ['basal cell carcinoma', 'melanoma', 'nevus', 'pigmented benign keratosis']
Number of training images: 1633
Number of test images: 64

In [11]:
train_size = int(0.8 * len(full_train_dataset))
val_size = len(full_train_dataset) - train_size

train_dataset, val_dataset = random_split(
    full_train_dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

print("Training images:", len(train_dataset))
print("Validation images:", len(val_dataset))
print("Test images:", len(test_dataset))

Training images: 1306
Validation images: 327
Test images: 64

In [12]:
BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("DataLoaders created successfully!")

DataLoaders created successfully!

In [13]:
transforms.Normalize(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225]
)

Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

In [14]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

IMG_SIZE = 224
BATCH_SIZE = 32

# ImageNet normalization
imagenet_mean = [0.485, 0.456, 0.406]
imagenet_std = [0.229, 0.224, 0.225]

# Training transformations
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=imagenet_mean,
        std=imagenet_std
    )
])

# Validation and test transformations
eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=imagenet_mean,
        std=imagenet_std
    )
])

In [15]:
import torch
from torchvision import datasets
from torch.utils.data import DataLoader, Subset

# Dataset without a transform, used only to get the image paths/classes
base_dataset = datasets.ImageFolder(
    train_path
)

# Create reproducible indices
generator = torch.Generator().manual_seed(42)

indices = torch.randperm(
    len(base_dataset),
    generator=generator
).tolist()

train_size = int(0.8 * len(indices))

train_indices = indices[:train_size]
val_indices = indices[train_size:]

# Training dataset with training augmentation
train_full = datasets.ImageFolder(
    train_path,
    transform=train_transform
)

# Validation dataset without random augmentation
val_full = datasets.ImageFolder(
    train_path,
    transform=eval_transform
)

# Create subsets using exactly the same indices
train_dataset = Subset(
    train_full,
    train_indices
)

val_dataset = Subset(
    val_full,
    val_indices
)

# Test dataset
test_dataset = datasets.ImageFolder(
    test_path,
    transform=eval_transform
)

print("Classes:", train_full.classes)
print("Training:", len(train_dataset))
print("Validation:", len(val_dataset))
print("Test:", len(test_dataset))

Classes: ['basal cell carcinoma', 'melanoma', 'nevus', 'pigmented benign keratosis']
Training: 1306
Validation: 327
Test: 64

In [16]:
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

Train batches: 41
Validation batches: 11
Test batches: 2

In [17]:
images, labels = next(iter(train_loader))

print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("Labels:", labels[:10])
print("Device:", "CUDA available" if torch.cuda.is_available() else "CPU")

Image batch shape: torch.Size([32, 3, 224, 224])
Label batch shape: torch.Size([32])
Labels: tensor([3, 2, 3, 0, 0, 3, 3, 2, 0, 2])
Device: CUDA available

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import numpy as np
import copy
import time

In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

num_classes = 4

print("Device:", device)
print("Number of classes:", num_classes)

Device: cuda
Number of classes: 4

# **AlexNet**

In [20]:
model = models.alexnet(
    weights=models.AlexNet_Weights.DEFAULT
)

# Replace the final classifier
model.classifier[6] = nn.Linear(
    model.classifier[6].in_features,
    num_classes
)

model = model.to(device)

print(model.classifier)

Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth

100%|██████████| 233M/233M [00:01<00:00, 186MB/s]

Sequential(
  (0): Dropout(p=0.5, inplace=False)
  (1): Linear(in_features=9216, out_features=4096, bias=True)
  (2): ReLU(inplace=True)
  (3): Dropout(p=0.5, inplace=False)
  (4): Linear(in_features=4096, out_features=4096, bias=True)
  (5): ReLU(inplace=True)
  (6): Linear(in_features=4096, out_features=4, bias=True)
)

In [21]:
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

print("Loss function:", criterion)
print("Optimizer:", optimizer.__class__.__name__)

Loss function: CrossEntropyLoss()
Optimizer: Adam

In [22]:
def train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
):

    best_model_wts = copy.deepcopy(model.state_dict())
    best_val_accuracy = 0.0

    epochs_without_improvement = 0

    history = {
        "train_loss": [],
        "train_accuracy": [],
        "val_loss": [],
        "val_accuracy": []
    }

    for epoch in range(num_epochs):

        start_time = time.time()

        # -------------------------
        # Training
        # -------------------------
        model.train()

        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item() * images.size(0)

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        train_loss = running_loss / total
        train_accuracy = correct / total

        # -------------------------
        # Validation
        # -------------------------
        model.eval()

        val_running_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item() * images.size(0)

                _, predicted = torch.max(outputs, 1)

                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        val_loss = val_running_loss / val_total
        val_accuracy = val_correct / val_total

        # Save history
        history["train_loss"].append(train_loss)
        history["train_accuracy"].append(train_accuracy)

        history["val_loss"].append(val_loss)
        history["val_accuracy"].append(val_accuracy)

        epoch_time = time.time() - start_time

        print(
            f"Epoch [{epoch+1}/{num_epochs}] "
            f"Train Loss: {train_loss:.4f} "
            f"Train Acc: {train_accuracy*100:.2f}% "
            f"Val Loss: {val_loss:.4f} "
            f"Val Acc: {val_accuracy*100:.2f}% "
            f"Time: {epoch_time:.1f}s"
        )

        # -------------------------
        # Best model
        # -------------------------
        if val_accuracy > best_val_accuracy:

            best_val_accuracy = val_accuracy

            best_model_wts = copy.deepcopy(
                model.state_dict()
            )

            epochs_without_improvement = 0

        else:

            epochs_without_improvement += 1

        # -------------------------
        # Early stopping
        # -------------------------
        if epochs_without_improvement >= patience:

            print("\nEarly stopping triggered.")

            break

    # Load best model
    model.load_state_dict(best_model_wts)

    print(
        f"\nBest Validation Accuracy: "
        f"{best_val_accuracy*100:.2f}%"
    )

    return model, history

In [23]:
trained_alexnet, alexnet_history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    num_epochs=10,
    patience=3
)

Epoch [1/10] Train Loss: 0.9657 Train Acc: 58.58% Val Loss: 0.7335 Val Acc: 69.11% Time: 25.4s
Epoch [2/10] Train Loss: 0.6754 Train Acc: 73.05% Val Loss: 0.6719 Val Acc: 72.78% Time: 25.0s
Epoch [3/10] Train Loss: 0.5833 Train Acc: 77.64% Val Loss: 0.6771 Val Acc: 73.70% Time: 23.3s
Epoch [4/10] Train Loss: 0.5185 Train Acc: 79.25% Val Loss: 0.5763 Val Acc: 77.98% Time: 24.9s
Epoch [5/10] Train Loss: 0.4217 Train Acc: 84.46% Val Loss: 0.5559 Val Acc: 77.68% Time: 24.4s
Epoch [6/10] Train Loss: 0.4010 Train Acc: 84.84% Val Loss: 0.6229 Val Acc: 75.84% Time: 23.6s
Epoch [7/10] Train Loss: 0.3499 Train Acc: 86.60% Val Loss: 0.5972 Val Acc: 77.06% Time: 24.3s

Early stopping triggered.

Best Validation Accuracy: 77.98%

In [24]:
def evaluate_model(model, test_loader, num_classes=4):

    model.eval()

    all_labels = []
    all_predictions = []
    all_probabilities = []

    with torch.no_grad():

        for images, labels in test_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            probabilities = torch.softmax(outputs, dim=1)

            _, predictions = torch.max(outputs, 1)

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())
            all_probabilities.extend(probabilities.cpu().numpy())

    all_labels = np.array(all_labels)
    all_predictions = np.array(all_predictions)
    all_probabilities = np.array(all_probabilities)

    # Accuracy
    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    # Precision
    precision = precision_score(
        all_labels,
        all_predictions,
        average="macro",
        zero_division=0
    )

    # Recall
    recall = recall_score(
        all_labels,
        all_predictions,
        average="macro",
        zero_division=0
    )

    # F1-score
    f1 = f1_score(
        all_labels,
        all_predictions,
        average="macro",
        zero_division=0
    )

    # Multiclass AUC
    auc = roc_auc_score(
        all_labels,
        all_probabilities,
        multi_class="ovr",
        average="macro"
    )

    results = {
        "Accuracy (%)": accuracy * 100,
        "Precision (%)": precision * 100,
        "Recall (%)": recall * 100,
        "F1-Score (%)": f1 * 100,
        "AUC (%)": auc * 100
    }

    return results

In [25]:
alexnet_results = evaluate_model(
    trained_alexnet,
    test_loader
)

print("AlexNet Test Results")
print("=" * 40)

for metric, value in alexnet_results.items():
    print(f"{metric}: {value:.2f}")

AlexNet Test Results
========================================
Accuracy (%): 75.00
Precision (%): 77.61
Recall (%): 75.00
F1-Score (%): 74.15
AUC (%): 90.66

# **VGG16**

In [26]:
def create_vgg16():

    model = models.vgg16(
        weights=models.VGG16_Weights.DEFAULT
    )

    # Replace final classifier
    model.classifier[6] = nn.Linear(
        model.classifier[6].in_features,
        num_classes
    )

    return model

In [27]:
vgg16_model = create_vgg16()

vgg16_model = vgg16_model.to(device)

print(vgg16_model.classifier)

Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth

100%|██████████| 528M/528M [00:04<00:00, 120MB/s]

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=4, bias=True)
)

In [28]:
vgg16_criterion = nn.CrossEntropyLoss()

vgg16_optimizer = optim.Adam(
    vgg16_model.parameters(),
    lr=0.0001
)

In [29]:
trained_vgg16, vgg16_history = train_model(
    model=vgg16_model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=vgg16_criterion,
    optimizer=vgg16_optimizer,
    num_epochs=10,
    patience=3
)

Epoch [1/10] Train Loss: 1.0844 Train Acc: 51.38% Val Loss: 0.9507 Val Acc: 59.63% Time: 33.3s
Epoch [2/10] Train Loss: 0.7358 Train Acc: 71.21% Val Loss: 0.6360 Val Acc: 74.31% Time: 28.7s
Epoch [3/10] Train Loss: 0.5824 Train Acc: 77.18% Val Loss: 0.4820 Val Acc: 82.26% Time: 29.1s
Epoch [4/10] Train Loss: 0.5223 Train Acc: 80.55% Val Loss: 0.5258 Val Acc: 79.82% Time: 29.9s
Epoch [5/10] Train Loss: 0.4708 Train Acc: 83.23% Val Loss: 0.5638 Val Acc: 80.73% Time: 30.4s
Epoch [6/10] Train Loss: 0.3905 Train Acc: 84.69% Val Loss: 0.5224 Val Acc: 80.12% Time: 29.6s

Early stopping triggered.

Best Validation Accuracy: 82.26%

In [30]:
vgg16_results = evaluate_model(
    trained_vgg16,
    test_loader
)

print("VGG16 Test Results")
print("=" * 40)

for metric, value in vgg16_results.items():
    print(f"{metric}: {value:.2f}")

VGG16 Test Results
========================================
Accuracy (%): 70.31
Precision (%): 72.63
Recall (%): 70.31
F1-Score (%): 66.12
AUC (%): 90.43

# **VGG19**

In [31]:
def create_vgg19():

    model = models.vgg19(
        weights=models.VGG19_Weights.DEFAULT
    )

    # Replace final classifier
    model.classifier[6] = nn.Linear(
        model.classifier[6].in_features,
        num_classes
    )

    return model

In [32]:
vgg19_model = create_vgg19()
vgg19_model = vgg19_model.to(device)

print(vgg19_model.classifier)

Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth

100%|██████████| 548M/548M [00:04<00:00, 118MB/s]

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=4, bias=True)
)

In [33]:
vgg19_criterion = nn.CrossEntropyLoss()

vgg19_optimizer = optim.Adam(
    vgg19_model.parameters(),
    lr=0.0001
)

In [34]:
trained_vgg19, vgg19_history = train_model(
    model=vgg19_model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=vgg19_criterion,
    optimizer=vgg19_optimizer,
    num_epochs=10,
    patience=3
)

Epoch [1/10] Train Loss: 1.2675 Train Acc: 40.66% Val Loss: 1.0269 Val Acc: 63.61% Time: 35.5s
Epoch [2/10] Train Loss: 0.8379 Train Acc: 64.93% Val Loss: 1.1720 Val Acc: 69.42% Time: 31.3s
Epoch [3/10] Train Loss: 0.7318 Train Acc: 72.28% Val Loss: 0.6301 Val Acc: 75.84% Time: 32.7s
Epoch [4/10] Train Loss: 0.6821 Train Acc: 75.04% Val Loss: 0.6952 Val Acc: 72.48% Time: 31.8s
Epoch [5/10] Train Loss: 0.5645 Train Acc: 78.64% Val Loss: 0.6030 Val Acc: 75.54% Time: 31.6s
Epoch [6/10] Train Loss: 0.5419 Train Acc: 79.79% Val Loss: 0.6532 Val Acc: 75.23% Time: 32.8s

Early stopping triggered.

Best Validation Accuracy: 75.84%

In [35]:
vgg19_results = evaluate_model(
    trained_vgg19,
    test_loader
)

print("VGG19 Test Results")
print("=" * 40)

for metric, value in vgg19_results.items():
    print(f"{metric}: {value:.2f}")

VGG19 Test Results
========================================
Accuracy (%): 68.75
Precision (%): 71.47
Recall (%): 68.75
F1-Score (%): 65.11
AUC (%): 92.35

# **ResNet18**

In [36]:
def create_resnet18():
    model = models.resnet18(
        weights=models.ResNet18_Weights.DEFAULT
    )

    model.fc = nn.Linear(
        model.fc.in_features,
        num_classes
    )

    return model


model = create_resnet18()
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

resnet18_results = evaluate_model(
    model,
    test_loader,
    num_classes=num_classes
)

print("\nResNet18 Test Results")
print("=" * 40)

for metric, value in resnet18_results.items():
    print(f"{metric}: {value:.2f}")

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

100%|██████████| 44.7M/44.7M [00:00<00:00, 129MB/s]

Epoch [1/10] Train Loss: 0.8735 Train Acc: 64.70% Val Loss: 0.6096 Val Acc: 76.15% Time: 23.9s
Epoch [2/10] Train Loss: 0.4571 Train Acc: 84.00% Val Loss: 0.5675 Val Acc: 77.98% Time: 23.4s
Epoch [3/10] Train Loss: 0.4008 Train Acc: 84.07% Val Loss: 0.6537 Val Acc: 75.84% Time: 23.9s
Epoch [4/10] Train Loss: 0.3141 Train Acc: 89.28% Val Loss: 0.5338 Val Acc: 81.96% Time: 24.0s
Epoch [5/10] Train Loss: 0.2768 Train Acc: 89.43% Val Loss: 0.5483 Val Acc: 82.57% Time: 24.3s
Epoch [6/10] Train Loss: 0.1991 Train Acc: 92.65% Val Loss: 0.5473 Val Acc: 83.79% Time: 24.4s
Epoch [7/10] Train Loss: 0.1759 Train Acc: 93.49% Val Loss: 0.6008 Val Acc: 81.35% Time: 22.9s
Epoch [8/10] Train Loss: 0.1694 Train Acc: 94.33% Val Loss: 0.5811 Val Acc: 80.12% Time: 24.3s
Epoch [9/10] Train Loss: 0.1509 Train Acc: 94.79% Val Loss: 0.6861 Val Acc: 79.20% Time: 24.8s

Early stopping triggered.

Best Validation Accuracy: 83.79%

ResNet18 Test Results
========================================
Accuracy (%): 70.31
Precision (%): 74.38
Recall (%): 70.31
F1-Score (%): 66.02
AUC (%): 93.20

# **ResNet50**

In [37]:
def create_resnet50():
    model = models.resnet50(
        weights=models.ResNet50_Weights.DEFAULT
    )

    model.fc = nn.Linear(
        model.fc.in_features,
        num_classes
    )

    return model


model = create_resnet50()
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

resnet50_results = evaluate_model(
    model,
    test_loader,
    num_classes=num_classes
)

print("\nResNet50 Test Results")
print("=" * 40)

for metric, value in resnet50_results.items():
    print(f"{metric}: {value:.2f}")

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:01<00:00, 86.7MB/s]

Epoch [1/10] Train Loss: 1.1515 Train Acc: 56.20% Val Loss: 0.7841 Val Acc: 72.48% Time: 27.9s
Epoch [2/10] Train Loss: 0.6101 Train Acc: 78.94% Val Loss: 0.5819 Val Acc: 78.59% Time: 26.5s
Epoch [3/10] Train Loss: 0.4214 Train Acc: 83.61% Val Loss: 0.5080 Val Acc: 80.73% Time: 26.4s
Epoch [4/10] Train Loss: 0.3403 Train Acc: 87.67% Val Loss: 0.5288 Val Acc: 78.90% Time: 26.7s
Epoch [5/10] Train Loss: 0.2697 Train Acc: 91.04% Val Loss: 0.4790 Val Acc: 84.71% Time: 26.0s
Epoch [6/10] Train Loss: 0.2266 Train Acc: 92.19% Val Loss: 0.5154 Val Acc: 82.57% Time: 30.9s
Epoch [7/10] Train Loss: 0.1761 Train Acc: 93.72% Val Loss: 0.5288 Val Acc: 85.02% Time: 32.6s
Epoch [8/10] Train Loss: 0.1530 Train Acc: 94.64% Val Loss: 0.6500 Val Acc: 79.51% Time: 26.4s
Epoch [9/10] Train Loss: 0.1262 Train Acc: 95.64% Val Loss: 0.5812 Val Acc: 81.96% Time: 27.2s
Epoch [10/10] Train Loss: 0.1044 Train Acc: 96.48% Val Loss: 0.6077 Val Acc: 81.96% Time: 26.7s

Early stopping triggered.

Best Validation Accuracy: 85.02%

ResNet50 Test Results
========================================
Accuracy (%): 78.12
Precision (%): 80.74
Recall (%): 78.12
F1-Score (%): 76.40
AUC (%): 90.98

# **ResNet101**

In [38]:
def create_resnet101():
    model = models.resnet101(
        weights=models.ResNet101_Weights.DEFAULT
    )

    model.fc = nn.Linear(
        model.fc.in_features,
        num_classes
    )

    return model


model = create_resnet101()
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

resnet101_results = evaluate_model(
    model,
    test_loader,
    num_classes=num_classes
)

print("\nResNet101 Test Results")
print("=" * 40)

for metric, value in resnet101_results.items():
    print(f"{metric}: {value:.2f}")

Downloading: "https://download.pytorch.org/models/resnet101-cd907fc2.pth" to /root/.cache/torch/hub/checkpoints/resnet101-cd907fc2.pth

100%|██████████| 171M/171M [00:01<00:00, 120MB/s]

Epoch [1/10] Train Loss: 1.1513 Train Acc: 54.44% Val Loss: 0.8161 Val Acc: 70.95% Time: 33.1s
Epoch [2/10] Train Loss: 0.6391 Train Acc: 75.88% Val Loss: 0.5637 Val Acc: 78.59% Time: 29.8s
Epoch [3/10] Train Loss: 0.4083 Train Acc: 85.99% Val Loss: 0.5008 Val Acc: 80.73% Time: 30.6s
Epoch [4/10] Train Loss: 0.2955 Train Acc: 89.43% Val Loss: 0.4762 Val Acc: 83.18% Time: 32.8s
Epoch [5/10] Train Loss: 0.2276 Train Acc: 91.58% Val Loss: 0.4780 Val Acc: 83.49% Time: 30.6s
Epoch [6/10] Train Loss: 0.1932 Train Acc: 93.11% Val Loss: 0.4845 Val Acc: 85.93% Time: 32.7s
Epoch [7/10] Train Loss: 0.1432 Train Acc: 95.41% Val Loss: 0.4935 Val Acc: 83.18% Time: 30.6s
Epoch [8/10] Train Loss: 0.1026 Train Acc: 96.55% Val Loss: 0.5128 Val Acc: 83.18% Time: 31.5s
Epoch [9/10] Train Loss: 0.1014 Train Acc: 96.55% Val Loss: 0.4978 Val Acc: 82.26% Time: 31.3s

Early stopping triggered.

Best Validation Accuracy: 85.93%

ResNet101 Test Results
========================================
Accuracy (%): 75.00
Precision (%): 83.17
Recall (%): 75.00
F1-Score (%): 70.78
AUC (%): 92.02

# **DenseNet121**

In [39]:
def create_densenet121():
    model = models.densenet121(
        weights=models.DenseNet121_Weights.DEFAULT
    )

    model.classifier = nn.Linear(
        model.classifier.in_features,
        num_classes
    )

    return model


model = create_densenet121()
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

densenet121_results = evaluate_model(
    model,
    test_loader,
    num_classes=num_classes
)

print("\nDenseNet121 Test Results")
print("=" * 40)

for metric, value in densenet121_results.items():
    print(f"{metric}: {value:.2f}")

Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to /root/.cache/torch/hub/checkpoints/densenet121-a639ec97.pth

100%|██████████| 30.8M/30.8M [00:00<00:00, 82.0MB/s]

Epoch [1/10] Train Loss: 0.9271 Train Acc: 62.48% Val Loss: 0.6833 Val Acc: 72.78% Time: 29.9s
Epoch [2/10] Train Loss: 0.5448 Train Acc: 78.94% Val Loss: 0.5734 Val Acc: 78.90% Time: 36.6s
Epoch [3/10] Train Loss: 0.3847 Train Acc: 86.29% Val Loss: 0.4971 Val Acc: 81.65% Time: 27.4s
Epoch [4/10] Train Loss: 0.3119 Train Acc: 88.97% Val Loss: 0.4834 Val Acc: 84.40% Time: 27.9s
Epoch [5/10] Train Loss: 0.2631 Train Acc: 90.81% Val Loss: 0.4720 Val Acc: 84.40% Time: 27.5s
Epoch [6/10] Train Loss: 0.1920 Train Acc: 93.64% Val Loss: 0.4762 Val Acc: 84.40% Time: 27.1s
Epoch [7/10] Train Loss: 0.1748 Train Acc: 94.64% Val Loss: 0.5186 Val Acc: 83.79% Time: 27.0s

Early stopping triggered.

Best Validation Accuracy: 84.40%

DenseNet121 Test Results
========================================
Accuracy (%): 70.31
Precision (%): 74.42
Recall (%): 70.31
F1-Score (%): 66.51
AUC (%): 90.79

# **EfficientNet-B0**

In [40]:
def create_efficientnet_b0():
    model = models.efficientnet_b0(
        weights=models.EfficientNet_B0_Weights.DEFAULT
    )

    model.classifier[1] = nn.Linear(
        model.classifier[1].in_features,
        num_classes
    )

    return model


model = create_efficientnet_b0()
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

efficientnet_b0_results = evaluate_model(
    model,
    test_loader,
    num_classes=num_classes
)

print("\nEfficientNet-B0 Test Results")
print("=" * 40)

for metric, value in efficientnet_b0_results.items():
    print(f"{metric}: {value:.2f}")

Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 175MB/s]

Epoch [1/10] Train Loss: 1.1958 Train Acc: 51.76% Val Loss: 0.9438 Val Acc: 68.50% Time: 24.5s
Epoch [2/10] Train Loss: 0.8046 Train Acc: 72.05% Val Loss: 0.6320 Val Acc: 79.20% Time: 25.9s
Epoch [3/10] Train Loss: 0.5783 Train Acc: 79.02% Val Loss: 0.5141 Val Acc: 83.18% Time: 25.1s
Epoch [4/10] Train Loss: 0.4574 Train Acc: 83.61% Val Loss: 0.5048 Val Acc: 84.10% Time: 24.6s
Epoch [5/10] Train Loss: 0.3699 Train Acc: 86.45% Val Loss: 0.4679 Val Acc: 84.10% Time: 24.5s
Epoch [6/10] Train Loss: 0.3244 Train Acc: 87.98% Val Loss: 0.4618 Val Acc: 84.71% Time: 25.2s
Epoch [7/10] Train Loss: 0.2748 Train Acc: 91.12% Val Loss: 0.4255 Val Acc: 84.71% Time: 24.7s
Epoch [8/10] Train Loss: 0.2207 Train Acc: 92.73% Val Loss: 0.4787 Val Acc: 83.18% Time: 25.1s
Epoch [9/10] Train Loss: 0.2039 Train Acc: 93.03% Val Loss: 0.4601 Val Acc: 84.10% Time: 25.1s

Early stopping triggered.

Best Validation Accuracy: 84.71%

EfficientNet-B0 Test Results
========================================
Accuracy (%): 71.88
Precision (%): 80.64
Recall (%): 71.88
F1-Score (%): 67.92
AUC (%): 93.72

# **Different Classifiers on ResNet50**

In [41]:
# ==========================================
# RESNET50 - BEST MODEL
# ==========================================

model = models.resnet50(
    weights=models.ResNet50_Weights.DEFAULT
)

model.fc = nn.Linear(
    model.fc.in_features,
    num_classes
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

model, history = train_model(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    num_epochs=10,
    patience=3
)

print("ResNet50 is ready for feature extraction.")

Epoch [1/10] Train Loss: 1.1794 Train Acc: 53.22% Val Loss: 0.8070 Val Acc: 74.01% Time: 33.1s
Epoch [2/10] Train Loss: 0.6564 Train Acc: 77.26% Val Loss: 0.5709 Val Acc: 79.51% Time: 27.8s
Epoch [3/10] Train Loss: 0.4531 Train Acc: 84.53% Val Loss: 0.4305 Val Acc: 84.10% Time: 28.4s
Epoch [4/10] Train Loss: 0.3563 Train Acc: 87.60% Val Loss: 0.4253 Val Acc: 85.02% Time: 28.3s
Epoch [5/10] Train Loss: 0.2660 Train Acc: 90.20% Val Loss: 0.4408 Val Acc: 84.10% Time: 29.1s
Epoch [6/10] Train Loss: 0.1946 Train Acc: 93.42% Val Loss: 0.4770 Val Acc: 83.49% Time: 28.0s
Epoch [7/10] Train Loss: 0.1587 Train Acc: 94.33% Val Loss: 0.5775 Val Acc: 83.18% Time: 27.8s

Early stopping triggered.

Best Validation Accuracy: 85.02%
ResNet50 is ready for feature extraction.

In [43]:
# ==========================================
# DEEP FEATURE EXTRACTION FROM RESNET50
# ==========================================

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from xgboost import XGBClassifier


# ------------------------------------------
# Create feature extractor
# ------------------------------------------

feature_extractor = nn.Sequential(
    *list(model.children())[:-1]
)

feature_extractor = feature_extractor.to(device)
feature_extractor.eval()


# ------------------------------------------
# Function to extract deep features
# ------------------------------------------

def extract_features(loader):

    features = []
    labels = []

    with torch.no_grad():

        for images, batch_labels in loader:

            images = images.to(device)

            outputs = feature_extractor(images)

            outputs = outputs.view(outputs.size(0), -1)

            features.append(outputs.cpu().numpy())
            labels.append(batch_labels.numpy())

    features = np.concatenate(features, axis=0)
    labels = np.concatenate(labels, axis=0)

    return features, labels


# ------------------------------------------
# Extract features
# ------------------------------------------

X_train, y_train = extract_features(train_loader)
X_val, y_val = extract_features(val_loader)
X_test, y_test = extract_features(test_loader)


# Combine train + validation
# because traditional classifiers
# do not use early stopping

X_train_full = np.concatenate(
    [X_train, X_val],
    axis=0
)

y_train_full = np.concatenate(
    [y_train, y_val],
    axis=0
)


print("Feature extraction completed.")
print("Training features:", X_train_full.shape)
print("Test features:", X_test.shape)


# ==========================================
# CLASSIFIERS
# ==========================================

classifiers = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),

    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),

    "K-Nearest Neighbors (KNN)": KNeighborsClassifier(
        n_neighbors=5
    ),

    "Linear SVM": SVC(
        kernel="linear",
        probability=True,
        random_state=42
    ),

    "RBF-SVM": SVC(
        kernel="rbf",
        probability=True,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="multi:softprob",
        num_class=num_classes,
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1
    )
}


# ==========================================
# TRAIN + EVALUATE
# ==========================================

results = []


for name, clf in classifiers.items():

    print("\n" + "=" * 50)
    print("Training:", name)
    print("=" * 50)

    clf.fit(
        X_train_full,
        y_train_full
    )

    predictions = clf.predict(X_test)

    probabilities = clf.predict_proba(X_test)


    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        average="macro",
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        average="macro",
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        average="macro",
        zero_division=0
    )

    auc = roc_auc_score(
        y_test,
        probabilities,
        multi_class="ovr",
        average="macro"
    )


    results.append({
        "Feature Extractor": "Deep Features (ResNet50)",
        "Classifier": name,
        "Accuracy (%)": accuracy * 100,
        "Precision (%)": precision * 100,
        "Recall (%)": recall * 100,
        "F1-Score (%)": f1 * 100,
        "AUC (%)": auc * 100
    })


# ==========================================
# FINAL TABLE
# ==========================================

results_df = pd.DataFrame(results)

results_df = results_df.round(2)

print("\n\nFINAL CLASSIFIER COMPARISON")
print("=" * 80)

display(results_df)

Feature extraction completed.
Training features: (1633, 2048)
Test features: (64, 2048)

==================================================
Training: Logistic Regression
==================================================

==================================================
Training: Decision Tree
==================================================

==================================================
Training: Random Forest
==================================================

==================================================
Training: K-Nearest Neighbors (KNN)
==================================================

==================================================
Training: Linear SVM
==================================================

==================================================
Training: RBF-SVM
==================================================

==================================================
Training: XGBoost
==================================================


FINAL CLASSIFIER COMPARISON
================================================================================

,Feature Extractor,Classifier,Accuracy (%),Precision (%),Recall (%),F1-Score (%),AUC (%)
0,Deep Features (ResNet50),Logistic Regression,76.56,80.57,76.56,74.42,90.98
1,Deep Features (ResNet50),Decision Tree,68.75,68.59,68.75,67.07,79.17
2,Deep Features (ResNet50),Random Forest,73.44,77.20,73.44,70.55,92.22
3,Deep Features (ResNet50),K-Nearest Neighbors (KNN),67.19,71.91,67.19,63.71,89.42
4,Deep Features (ResNet50),Linear SVM,75.00,77.18,75.00,73.13,91.60
5,Deep Features (ResNet50),RBF-SVM,75.00,79.72,75.00,72.36,94.11
6,Deep Features (ResNet50),XGBoost,75.00,79.72,75.00,72.36,90.76

# **Computational Efficiency Comparison**

In [45]:
!pip install thop -q

In [46]:
# ==========================================
# TABLE 3 - COMPUTATIONAL EFFICIENCY
# ==========================================

import torch
import torch.nn as nn
import pandas as pd
import time

from torchvision import models
from thop import profile


# ------------------------------------------
# Settings
# ------------------------------------------

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

IMG_SIZE = 224
NUM_CLASSES = 4

dummy_input = torch.randn(
    1, 3, IMG_SIZE, IMG_SIZE
).to(device)


# ------------------------------------------
# Create models
# ------------------------------------------

model_creators = {

    "AlexNet": lambda: models.alexnet(
        weights=models.AlexNet_Weights.DEFAULT
    ),

    "VGG16": lambda: models.vgg16(
        weights=models.VGG16_Weights.DEFAULT
    ),

    "VGG19": lambda: models.vgg19(
        weights=models.VGG19_Weights.DEFAULT
    ),

    "ResNet18": lambda: models.resnet18(
        weights=models.ResNet18_Weights.DEFAULT
    ),

    "ResNet50": lambda: models.resnet50(
        weights=models.ResNet50_Weights.DEFAULT
    ),

    "DenseNet121": lambda: models.densenet121(
        weights=models.DenseNet121_Weights.DEFAULT
    ),

    "EfficientNet-B0": lambda: models.efficientnet_b0(
        weights=models.EfficientNet_B0_Weights.DEFAULT
    )
}


# ------------------------------------------
# Modify final layers to 4 classes
# ------------------------------------------

def prepare_model(name, model):

    if name == "AlexNet":
        model.classifier[6] = nn.Linear(
            model.classifier[6].in_features,
            NUM_CLASSES
        )

    elif name in ["VGG16", "VGG19"]:
        model.classifier[6] = nn.Linear(
            model.classifier[6].in_features,
            NUM_CLASSES
        )

    elif name in ["ResNet18", "ResNet50"]:
        model.fc = nn.Linear(
            model.fc.in_features,
            NUM_CLASSES
        )

    elif name == "DenseNet121":
        model.classifier = nn.Linear(
            model.classifier.in_features,
            NUM_CLASSES
        )

    elif name == "EfficientNet-B0":
        model.classifier[1] = nn.Linear(
            model.classifier[1].in_features,
            NUM_CLASSES
        )

    return model


# ------------------------------------------
# Measure inference time
# ------------------------------------------

def measure_inference_time(model, repetitions=100):

    model.eval()

    # Warm-up
    with torch.no_grad():
        for _ in range(10):
            _ = model(dummy_input)

    if device.type == "cuda":
        torch.cuda.synchronize()

    start_time = time.perf_counter()

    with torch.no_grad():
        for _ in range(repetitions):
            _ = model(dummy_input)

    if device.type == "cuda":
        torch.cuda.synchronize()

    total_time = time.perf_counter() - start_time

    avg_time_ms = (
        total_time / repetitions
    ) * 1000

    return avg_time_ms


# ------------------------------------------
# Accuracy from your experiments
# ------------------------------------------

accuracy_values = {

    "AlexNet": 75.00,

    "VGG16": 70.31,

    "VGG19": 68.75,

    "ResNet18": 70.31,

    "ResNet50": 78.12,

    "DenseNet121": 70.31,

    "EfficientNet-B0": 71.88
}


# ------------------------------------------
# Calculate everything
# ------------------------------------------

results = []


for name, creator in model_creators.items():

    print("\n" + "=" * 50)
    print("Processing:", name)
    print("=" * 50)

    model = creator()

    model = prepare_model(
        name,
        model
    )

    model = model.to(device)

    model.eval()


    # -----------------------------
    # Parameters
    # -----------------------------

    total_parameters = sum(
        p.numel()
        for p in model.parameters()
    )

    parameters_m = (
        total_parameters / 1_000_000
    )


    # -----------------------------
    # Model size
    # -----------------------------

    # Each float32 parameter = 4 bytes
    model_size_mb = (
        total_parameters * 4
    ) / (1024 ** 2)


    # -----------------------------
    # FLOPs
    # -----------------------------

    flops, params = profile(
        model,
        inputs=(dummy_input,),
        verbose=False
    )

    flops_g = (
        flops / 1_000_000_000
    )


    # -----------------------------
    # Inference time
    # -----------------------------

    inference_time = measure_inference_time(
        model,
        repetitions=100
    )


    # -----------------------------
    # Store results
    # -----------------------------

    results.append({

        "Model": name,

        "Parameters (M)": parameters_m,

        "Model Size (MB)": model_size_mb,

        "FLOPs (G)": flops_g,

        "Inference Time (ms)": inference_time,

        "Accuracy (%)": accuracy_values[name]
    })


    print(
        f"Parameters: {parameters_m:.2f} M"
    )

    print(
        f"Model Size: {model_size_mb:.2f} MB"
    )

    print(
        f"FLOPs: {flops_g:.2f} G"
    )

    print(
        f"Inference Time: {inference_time:.2f} ms"
    )

    print(
        f"Accuracy: {accuracy_values[name]:.2f}%"
    )


# ------------------------------------------
# Final Table 3
# ------------------------------------------

table3 = pd.DataFrame(results)

table3 = table3.round({
    "Parameters (M)": 2,
    "Model Size (MB)": 2,
    "FLOPs (G)": 2,
    "Inference Time (ms)": 2,
    "Accuracy (%)": 2
})


print("\n\n")
print("=" * 90)
print("TABLE 3. COMPUTATIONAL EFFICIENCY COMPARISON")
print("=" * 90)

display(table3)

==================================================
Processing: AlexNet
==================================================
Parameters: 57.02 M
Model Size: 217.51 MB
FLOPs: 0.71 G
Inference Time: 3.75 ms
Accuracy: 75.00%

==================================================
Processing: VGG16
==================================================
Parameters: 134.28 M
Model Size: 512.23 MB
FLOPs: 15.47 G
Inference Time: 10.58 ms
Accuracy: 70.31%

==================================================
Processing: VGG19
==================================================
Parameters: 139.59 M
Model Size: 532.48 MB
FLOPs: 19.63 G
Inference Time: 12.82 ms
Accuracy: 68.75%

==================================================
Processing: ResNet18
==================================================
Parameters: 11.18 M
Model Size: 42.64 MB
FLOPs: 1.82 G
Inference Time: 8.56 ms
Accuracy: 70.31%

==================================================
Processing: ResNet50
==================================================
Parameters: 23.52 M
Model Size: 89.71 MB
FLOPs: 4.13 G
Inference Time: 13.84 ms
Accuracy: 78.12%

==================================================
Processing: DenseNet121
==================================================
Parameters: 6.96 M
Model Size: 26.54 MB
FLOPs: 2.90 G
Inference Time: 17.78 ms
Accuracy: 70.31%

==================================================
Processing: EfficientNet-B0
==================================================
Parameters: 4.01 M
Model Size: 15.31 MB
FLOPs: 0.41 G
Inference Time: 12.06 ms
Accuracy: 71.88%



==========================================================================================
TABLE 3. COMPUTATIONAL EFFICIENCY COMPARISON
==========================================================================================

,Model,Parameters (M),Model Size (MB),FLOPs (G),Inference Time (ms),Accuracy (%)
0,AlexNet,57.02,217.51,0.71,3.75,75.00
1,VGG16,134.28,512.23,15.47,10.58,70.31
2,VGG19,139.59,532.48,19.63,12.82,68.75
3,ResNet18,11.18,42.64,1.82,8.56,70.31
4,ResNet50,23.52,89.71,4.13,13.84,78.12
5,DenseNet121,6.96,26.54,2.90,17.78,70.31
6,EfficientNet-B0,4.01,15.31,0.41,12.06,71.88